### ISSUE TITLE
关于 JasperReport 字体问题

### ISSUE THREAD

**Issue by sozcos** [richso/hkmlApp#1]
你好, 我在浏览 JasperReport 的 issues 关于字体问题的时候看到你提出的问题,
有个问题我想请问下, 就是关于中文内容我要如何引入字体?

我在 resource 目录下添加了 配置, 本地 win 系统没有问题, 但是应用部署到 linux docker 容器内会一直提示:
Font "华文宋体" is not available to the JVM. See the Javadoc for more details

请问您这边有遇到此类问题吗? 这让我狠困扰

**Comment by richso** [comment]
Firstly, I think you should not ask other things via my this Github instance; you should ask your questions in the relevant, i.e. JasperReport Github instead.

On you question, I recommend you to checkout the Jaspersoft Studio Community Version: https://community.jaspersoft.com/files/file/19-jaspersoft%C2%AE-studio-community-edition/
which is a free software for creating report templates for using together with JasperReport library or even JasperReport Server; in which there is a function to package up fonts into Jar Java libraries. These Font Jar libraries can be used with JasperReport library / Server to provide the fonts to be using in generating the reports

**Comment by sozcos** [comment]
thanks bro!
